---
- name: (takelscripts) copy entry script
  copy:
    src: takelscripts/entrypoint.py
    dest: "{{ takel_takelage_entrypoint_path }}entrypoint.py"
    mode: 0755

- name: (takelscripts) copy login script
  copy:
    src: takelscripts/loginpoint.py
    dest: "{{ takel_takelage_entrypoint_path }}loginpoint.py"
    mode: 0755

- name: (takelscripts) copy takelage script
  copy:
    src: takelscripts/takelage.py
    dest: /usr/local/bin/takelage
    mode: 0755
