---
takel_takelage_deb_install_packages:
  - chromium
  - cloc
  - expect
  - git
  - gnupg
  - postgresql-client
  - pwgen
  - python3-docker
  - socat
  - sudo

takel_takelage_gpg_config_files:
  - gpg-agent.conf
  - gpg.conf
  - dirmngr.conf

takel_takelage_entrypoint_path: /

takel_takelage_profile:
  - file: aliases.sh
    order: 50
  - file: make.sh
    order: 50
  - file: prompt.sh
    order: 50
  - file: sshagent.sh
    order: 50
  - file: tau.sh
    order: 50
